
#CC65HOME ?=

# c64/cbm tools
PUCRUNCH ?= pucrunch
C1541 ?= c1541
PETCAT ?= petcat

# gamate tools
GFIX ?= gamate-fixcart

# apple2 tools

# this must point to the .jar file of "AppleCommander"
ACMD ?= ac.jar

# atari tools
DIR2ATR ?= dir2atr

################################################################################
# Emulators - You don't need these for building
################################################################################

X64SC ?= x64sc
X128 ?= x128
XVIC ?= xvic
XPLUS4 ?= xplus4
XPET ?= xpet
XCBM5 ?= xcbm5x0
XCBM6 ?= xcbm2

ATARI8EMU ?= atari800 -atari -windowed -run
ATARI8XLEMU ?= atari800 -xl -windowed -run

#NESEMU ?= InfoNES
#NESEMU ?= fceu -pal
#NESEMU ?= fceux
NESEMU ?= mednafen -force_module nes

#PCEEMU ?= xvpce
#PCEEMU ?= xyame -f 0
PCEEMU ?= mednafen -force_module pce

#APPLE2EMU ?= linapple --autoboot --d1 
#APPLE2EMU ?= wine Applewin.exe -d1
APPLE2EMU ?= Applewin -d1
